# .gitea/workflows/ci-tests.yml
name: CI-Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: dotnet-10
    strategy:
      matrix:
        framework: [net8.0, net10.0]
    steps:
      - run: dotnet --info
      - uses: actions/checkout@v5
      - run: dotnet test -f ${{ matrix.framework }}
