<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net10.0</TargetFrameworks>
    <PackageId>aqua-core</PackageId>
    <PackageTags>type-info;dynamic-object;expando-object;object-mapping;object-mapper</PackageTags>
    <Description>
      Transform any object-graph into a dynamic, composed dictionaries like structure, holding serializable values and type information.

      Commonly Used Types:
      Aqua.Dynamic.DynamicObject
      Aqua.Dynamic.DynamicObjectMapper
      Aqua.TypeSystem.ConstructorInfo
      Aqua.TypeSystem.FieldInfo
      Aqua.TypeSystem.MethodInfo
      Aqua.TypeSystem.TypeInfo
      Aqua.TypeSystem.PropertyInfo
    </Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Aqua.Tests, PublicKey=0024000004800000940000000602000000240000525341310004000001000100953fd5a46105ee9924e16998b8d7cad276601925390edd925c567e11a6d22ad43f35db27a94b2b3288886ddbb56053f3310bb7707ea653b2aed436936aea7aa6ddea4598a4eb9516aafcc3e26ff3e370a57634380aa7af3a678e96c00aacca6d460cbb7c9d2bdbed375a40cf89430a404314bec9b7f4498b24017548f3dd92ed" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Reflection.Emit" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netstandard2.1' ">
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

</Project>